# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd447f484d17a63963d313b6dd32a301208dfa41f69ec13985efccd28b3415db6416cdb69d3db27937ccf787d80bbf6dca4f2e255856f5e74ecbb2277b6cf80f

test:
  secret_key_base: 23ef6746b01726c463103beb4f481c61a51561b37896dc09ba0043d6f5dd77a5f54c4fcb0ffb87f4303ba79014e159afcb9c36c74416c9b276a7b8f4cc9e8310

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
